#!/bin/sh

yay -Sy \
  adobe-source-han-sans-otc-fonts \
  adobe-source-han-serif-otc-fonts \
  alsa \
  asdf-vm \
  atom \
  betterlockscreen-git \
  bluez \
  bluez-utils \
  cheese \
  conky \
  dropbox \
  dunst \
  firefox \
  fish \
  flameshot \
  gnome-themes-extra \
  htop \
  hub \
  lib32-libva-mesa-driver \
  lib32-mesa \
  lib32-mesa-vdpau \
  lib32-vulkan-radeon \
  libxft-bgra-git \
  logiops \
  man-db \
  mesa-vdpau \
  nfs-utils \
  nitrogen \
  onboard \
  openssh \
  otf-libertinus \
  otf-san-francisco \
  pamixer \
  pulseaudio \
  pulseaudio-alsa \
  pulseaudio-bluetooth \
  python \
  redshift \
  st-luke-git \
  steam \
  telegram-desktop \
  tex-gyre-fonts \
  tig \
  ttf-apple-emoji \
  ttf-fira-code \
  vim \
  xcape \
  xidlehook \
  xkeysnail \
  xorg-xrandr \
  xorg-xrdb \
  xorg-xset \
  xscreensaver \
  xscreensaver-aerial
