set clipboard+=unnamedplus           " Use system clipboard
set colorcolumn=80                   " Set an 80 width column border
set expandtab                        " Use space instead of tabs
set ignorecase                       " Case insensitive search
set number                           " Display line numbers
set scrolloff=8                      " Keep 8 lines above/below cursor
set shiftwidth=2                     " Shift by 2 spaces when using << >>
set smartcase                        " Case sensitive if uppercase present
set ts=2 sts=2                       " Set tab to 2 spaces
set undofile                         " Save undo history

                                     " Keep selection when reindenting
vnoremap < <gv
vnoremap > >gv

autocmd BufWritePre * :%s/\s\+$//e   " Remove trailing \s
autocmd BufWritePre * :%s/\n\+\%$//e " Remove trailing \n
