# Essential programs
brew "bat"
brew "btop"
brew "curl"
brew "doggo"
brew "duf"
brew "dust"
brew "entr"
brew "fish"
brew "fzf"
brew "gh"
brew "git"
brew "git-delta"
brew "gping"
brew "hexyl"
brew "htop"
brew "lsd"
brew "mas"
brew "mosh"
brew "neovim"
brew "nmap"
brew "overmind"
brew "ripgrep"
brew "ssh-copy-id"
brew "stow"
brew "tig"
brew "tmux"
brew "tree"
brew "wakeonlan"
brew "watch"
brew "wget"
brew "zoxide"

# Games and fun stuff
brew "cmatrix"
brew "cowsay"
brew "figlet"
brew "fortune"
brew "nethack"
brew "sl"

# Native apps
cask "1password"
cask "alfred"
cask "appcleaner"
cask "audacity"
cask "beeper"
cask "calibre"
cask "cursor"
cask "daisydisk"
cask "dash"
cask "docker"
cask "font-iosevka-nerd-font"
cask "google-chrome"
cask "istat-menus"
cask "logi-options+"
cask "lunar"
cask "msty"
cask "parsec"
cask "rectangle"
cask "slack"
cask "spotify"
cask "steam"
cask "the-unarchiver"
cask "transmission"
cask "vlc"
cask "whisky"

# Mac App Store apps
mas "1password-safari", id: 1569813296
mas "amphetamine", id: 937984704
mas "hush", id: 1544743900
mas "refined-github", id: 1519867270
mas "vimari", id: 1480933944
mas "wireguard", id: 1451685025
